### ISSUE TITLE
Failure to load

### ISSUE THREAD

**Issue by jasskin** [CKNOEP/Necrosis#19]
153x Necrosis/XML/Attributes.lua:221: attempt to concatenate local 'Rank1' (a boolean value)
[string "@Necrosis/XML/Attributes.lua"]:221: in function `SetBuffSpellAttribute'
[string "@Necrosis/XML/Attributes.lua"]:266: in function `BuffSpellAttribute'
[string "@Necrosis/Necrosis.lua"]:861: in function <Necrosis/Necrosis.lua:849>
[string "@Necrosis/Necrosis.lua"]:1396: in function `OnEvent'
[string "@Necrosis/Initialize.lua"]:48: in function <Necrosis/Initialize.lua:47>

Locals:
self = <table> {
 IsSpellStone = <function> defined @Necrosis/Spells.lua:1187
 SetItem = <function> defined @Necrosis/Dialog.lua:48
 IsSpellMount = <function> defined @Necrosis/Spells.lua:1101
 RezTimerUpdate = <function> defined @Necrosis/Timers/OtherTimers.lua:55
 Unit = <table> {
 }
 InitWarlockItems = <function> defined @Necrosis/Dialog.lua:96
 TextTimerUpdate = <function> defined @Necrosis/Timers/OtherTimers.lua:107
 ButtonSetup = <function> defined @Necrosis/Necrosis.lua:2511
 Timer_Click = <function> defined @Necrosis/XML/Options-Timers.lua:347
 RemoveTimerByNameAndGuid = <function> defined @Necrosis/Timers/Functions.lua:344
 Localization_Speech_Es = <function> defined @Necrosis/Speech/Speech-es.lua:6
 IsSpellKnownId = <function> defined @Necrosis/Spells.lua:943
 BuffVector_Click = <function> defined @Necrosis/XML/Options-Menus.lua:818
 SetCompanionPage = <function> defined @Necrosis/XML/Options-Buttons.lua:493
 TimerManagement = <table> {
 }
 GetSpell = <function> defined @Necrosis/Spells.lua:1009
 SetPetSpellAttribute = <function> defined @Necrosis/XML/Attributes.lua:272
 Msg = <function> defined @Necrosis/Message.lua:17
 AddFrame = <function> defined @Necrosis/Timers/GraphicalTimers.lua:101
 HealthstoneCooldown = "|c00FFFFFFNecrosis|r"
 InCombatAttribute = <function> defined @Necrosis/XML/Attributes.lua:715
 NameDemon = <table> {
 }
 RetraitTimerParGuid = <function> defined @Necrosis/Timers/Functions.lua:316
 BuffSpellAttribute = <function> defined @Necrosis/XML/Attributes.lua:255
 Sacrifice_Init = <function> defined @Necrosis/XML/Options-Menus.lua:800
 Warlock_Lists = <table> {
 }
 MenuAttribute = <function> defined @Necrosis/XML/Attributes.lua:77
 IsHealthStone = <function> defined @Necrosis/Spells.lua:1144
 CreateWarlockUI = <function> defined @Necrosis/XML/XML.lua:57
 GetCompanionInfo = <function> defined @Necrosis/Necrosis.lua:2940
 Event_Init = <function> defined @Necrosis/XML/Options-Sphere.lua:264
 Speech_It = <function> defined @Necrosis/Message.lua:153
 SetTimersConfig = <function> defined @Necrosis/XML/Options-Timers.lua:14
 Event_Click = <function> defined @Necrosis/XML/Options-Sphere.lua:276
 GetItemList = <function> defined @Necrosis/Dialog.lua:78
 HealthstoneUpdateAttribute = <function> defined @Necrosis/XML/Attributes.lua:822
 GetSpellMana = <function> defined @Necrosis/Spells.lua:978
 SetMessagesConfig = <function> defined @Necrosis/XML/Options-Messages.lua:36
 StoneAttribute = <function> defined @Necrosis/XML/Attributes.lua:399
 TooltipData = <table> {
 }
 UpdateHealth = <function> defined @Necrosis/Necrosis.lua:2042
 Translation = <table> {
 }
 SymetrieTimer = <function> defined @Necrosis/Necrosis.lua:2952
 GetItemNames = <function> defined @Necrosis/Dialog.lua:82
 Speech = <table> {
 }
 UpdateSpellTimers = <function> defined @Necrosis/Spells.lua:921
 CreateWarlockPopup = <function> defined @Necrosis/XML/XML.lua:377
 ChatMessage = <table> {
 }
 SpellSetup = <function> defined @Necrosis/Spells.lua:1254
 Sound = <table> {
 }
 Sacrifice_Click = <function> defined @Necrosis/XML/Options-Menus.lua:811
 Debug = <table> {
 }
 CreateMenu = <function> defined @Necrosis/Necrosis.lua:2666
 GetItem = <function> defined @Necrosis/Dialog.lua:86
 GetSpellRank = <function> defined @Necrosis/Spells.lua:988
 BuildButtonTooltip = <function> defined @Necrosis/Ne

**Comment by Thulium-Drake** [comment]
I don't use the spell menu, so I commented out line 221 and 222 in the attributes.lua file to workaround this issue :)

**Comment by CKNOEP** [comment]
Fix in the last version , ty
