### ISSUE TITLE
[WotLK] fix SendChatMessage error in random dungeon Instance

### ISSUE THREAD

**Issue by simshi** [CKNOEP/Necrosis#24]
https://github.com/CKNOEP/Necrosis/blob/4a5ee3493587b584128cfea991fd6918bdfd7769/Message.lua#L29-L39

`SendChatMessage` by party errors with something like "not in a party", it can be fixed by below code:

```lua
		elseif IsInGroup(LE_PARTY_CATEGORY_INSTANCE) then
			SendChatMessage(msg, "INSTANCE_CHAT")
		elseif UnitInParty("player") then
			-- send to party members
			SendChatMessage(msg, "PARTY")
```

**Comment by CKNOEP** [comment]
thanks a lot , have fun
