### ISSUE TITLE
Firestone rank 4 is cast, despite rank 5 being available.

### ISSUE THREAD

**Issue by hazadar** [CKNOEP/Necrosis#4]
Given I am level 66 or higher
And I have trained Firestone Rank 5
When I click the Firestone button
Then I should create the max rank Firestone available to me

line 264, Spells.lua:
`	[27250] = {UsageRank = 4, SpellRank = 5, Timer = false, Usage = "firestone",},`

Needs to become:

line 264, Spells.lua:
`	[27250] = {UsageRank = 5, SpellRank = 5, Timer = false, Usage = "firestone",},`

**Comment by CKNOEP** [comment]
fix
