### ISSUE TITLE
Graphic Bug?

### ISSUE THREAD

**Issue by Rafa28062013** [CKNOEP/Necrosis#7]
Hei,

i have some Graphic Bug, You can see it on the Screenshot what i mean. What can i do?

![Screenshot (318)](https://user-images.githubusercontent.com/79382964/127748080-5cf8b566-7fe7-4267-9480-0a65f0476739.png)

**Comment by CKNOEP** [comment]
hi sir warlock.
this probably comes from a corrupted update, can you try to do a complete installation, or else the command / necrosis reset
